variables:
  IMAGE: $CI_REGISTRY_IMAGE
  VERSION: "0.0.5"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:dind
    command:
      - "dockerd-entrypoint.sh"
      - "--registry-mirror"
      - "https://dockerhub.azk8s.cn"

stages:
  - test
  - build
  - deploy

# Lint and build test.
test:
  stage: test
  image: node:10.15.3-slim
  allow_failure: false
  cache:
    key: cache-key
    paths:
      - dist/
  script:
    - npm install --registry=https://registry.npm.taobao.org
    - npm run lint
    - npm run build
  except:
    - master
    - /^.*-no-test$/i

build:
  stage: build
  image: docker
  allow_failure: false
  cache:
    key: cache-key
    paths:
      - dist/
    policy: pull
  variables:
    DOCKER_HOST: tcp://localhost:2375
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE || true
  script:
    - docker build --cache-from $IMAGE:latest -t $IMAGE .
    - docker push $IMAGE
  only:
    - development

deploy:
  stage: deploy
  image: lachlanevenson/k8s-kubectl
  allow_failure: false
  environment:
    name: production
  script:
    - sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories && apk update --no-cache && apk add gettext curl
    - kubectl -n $KUBE_NAMESPACE create secret docker-registry ${CI_PROJECT_NAME}-pull-secret --docker-server="$CI_REGISTRY" --docker-username="$GITLAB_DEPLOY_USER" --docker-password="$GITLAB_DEPLOY_TOKEN" --docker-email="$GITLAB_USER_EMAIL" -o yaml --dry-run | kubectl apply -f -
    - envsubst < deployment.yaml | kubectl apply -f -
  only:
    - master

    